### ISSUE TITLE
Need archetypes for smaller projects

### ISSUE THREAD

**Issue by jberkus** [OpenTechStrategies/open-source-archetypes#5]
All of the archetypes currently offered refer only to large, or at least well-established, projects.  I would argue that there are a few others that apply to smaller projects.  Ideas:

* Language Module: any specific, non-core, module for a programming language. Frequently maintained by a single developer, with drive-by contributions from advanced users.
* The Scratched Itch: single-developer or small-team project which was developed just to solve a personal/departmental problem and then open-sourced.
* The Viable Fork: successful fork of another project established because of a desire for domain-specific changes, licensing, governance, or other changes to an establish project.

Others?

**Comment by jvasile** [comment]
We originated this work in the context of Mozilla, so it's no surprise we didn't consider smaller efforts.  I agree it's an oversight.

**Comment by kfogel** [comment]
I agree, there's at least one archetype missing here -- call it the "single-developer scratched itch".  Uh, okay, don't call it that, because it's a terrible name, but you get the idea.  (We'll think of a better name.)

Often a language module is something that was started to solve a personal/departmental problem -- i.e., sometimes these itches are scratched via standalone programs, and sometimes via language-specific modules, but it's basically the same thing in both cases, archetype-wise.

Viable Fork strikes me as a different thing altogether, because forks can be of any size (remember when GCC got forked?), and a fork can both come from any archetype and be any archetype itself.  I.e., I think the fact of being forked is mostly independent of archetype.

**Comment by kfogel** [comment]
To the extent this issue can be "resolved", I think it is.  The material I added in those commits might get moved around, the archetype might get renamed, etc, but at any rate tracking is now happening in the doc rather than here.  So I'll close this ticket.  Thanks, @jberkus, for the suggestion.
